#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_
/* Timer0 Mode options:
 * 1- TIMER0_NORMAL_MODE
 * 2- TIMER0_CTC_MODE
 * 3- TIMER0_PWM_PHASECORRECT_MODE
 * 4- TIMER0_PWM_FAST_MODE
 */

#define TIMER0_MODE  TIMER0_NORMAL_MODE

/*PRESCALER OPTIONS:
   1- TIMER0_NO_PRESCALER
   2- TIMER0_8_PRESCALER
   3- TIMER0_64_PRESCALER
   4- TIMER0_256_PRESCALER
   5- TIMER0_1024_PRESCALER
   6- TIMER0_EXTERNAL_SOURCE_FALLING
   7- TIMER0_EXTERNAL_SOURCE_RISING
   */
#define TIMER0_PRESCALER  TIMER0_1024_PRESCALER
#define TIMER0_PRELOAD    212
#endif /* TIMER_CONFIG_H_ */
